### ISSUE TITLE
split_responses() for surveys doesn't include embedded survey items 

### ISSUE THREAD

**Issue by maryctucker** [UCLATALL/CourseKataData#4]
@adamblake The split_responses() function only includes survey items that are included on the pre- and post course surveys. But there are several survey questions embedded within the online textbooks. We need to update the function so that all survey items are included as surveys instead of in-text items.

**Comment by adamblake** [comment]
Is there already a list of the IDs for the survey items?

**Comment by adamblake** [comment]
Resolved by b55bff0b524e416ed3d6f6e17d563a7493341c65
