### ISSUE TITLE
no school_id variable in any of the download files

### ISSUE THREAD

**Issue by maryctucker** [UCLATALL/CourseKataData#6]
@adamblake It would be helpful if we could generate a unique school_id (similar to teacher_id and class_id) that is available to researchers in the download. Now, there is now way to identify teachers and classes that are nested within the same school unless researchers do it manually based on information in the CourseKata research page.

**Comment by adamblake** [comment]
Created ticket on Jira: [BB-579](https://betterbook.atlassian.net/browse/BB-579?atlOrigin=eyJpIjoiMTIwMzdjYjhhMzkwNDc4NDkwYTEzNjc2NjEwODYxYjIiLCJwIjoiaiJ9)

**Comment by adamblake** [comment]
This is now available as `institution_id` on all of the CSVs in the data downloads. I updated the wiki as well
